-- ========================================
-- CREATE GPS DUTY NUMBERS TABLE
-- Run this in the Supabase SQL Editor
-- ========================================

create table if not exists public.gps_duty_numbers (
  id bigint generated by default as identity primary key,
  duty_type text not null check (duty_type in ('night', 'keyman')),
  position integer not null check (position >= 0),
  gps_number text not null default '',
  updated_by uuid references auth.users (id) on delete set null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint gps_duty_numbers_type_position_key unique (duty_type, position)
);

alter table public.gps_duty_numbers enable row level security;

drop policy if exists "gps_numbers_select" on public.gps_duty_numbers;
create policy "gps_numbers_select" on public.gps_duty_numbers
  for select
  to authenticated
  using (true);

drop policy if exists "gps_numbers_insert" on public.gps_duty_numbers;
create policy "gps_numbers_insert" on public.gps_duty_numbers
  for insert
  to authenticated
  with check (true);

drop policy if exists "gps_numbers_update" on public.gps_duty_numbers;
create policy "gps_numbers_update" on public.gps_duty_numbers
  for update
  to authenticated
  using (true)
  with check (true);

insert into public.gps_duty_numbers (duty_type, position, gps_number)
values
  ('night', 0, '# 103011'),
  ('night', 1, '# 103249'),
  ('night', 2, '# 103237'),
  ('night', 3, '# 303121'),
  ('night', 4, '# 103098'),
  ('night', 5, '# 103116'),
  ('keyman', 0, '80083'),
  ('keyman', 1, '86639'),
  ('keyman', 2, '85437'),
  ('keyman', 3, '86484'),
  ('keyman', 4, '102861'),
  ('keyman', 5, '80444'),
  ('keyman', 6, '85195'),
  ('keyman', 7, '80374')
on conflict (duty_type, position) do update
set
  gps_number = excluded.gps_number,
  updated_at = timezone('utc', now());
